name: Run Tests

on:
  pull_request:
    branches: [ "main" ]

  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        type: [smoke, full]

    steps:
      - name: Checkout code 🧬
        uses: actions/checkout@v3

      - name: Set up JDK 25 ☕
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Run Smoke Tests 🚀
        if: github_event_name == "pull_request"
        run: mvn clean test -DincludeTags=smoke
        env:
          TOKEN_FOR_GIST: ${{secrets.TOKEN_FOR_GIST}}

      - name: Run Regression Tests 🚀
        if: github_event_name == "push"
        run: mvn clean test -DincludeTags=regression
        env:
          TOKEN_FOR_GIST: ${{secrets.TOKEN_FOR_GIST}}
